kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-elk-1
  namespace: elk
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv1"
